enum ErrorCodes {
  ER_UNEXP,
  ER_EMAIL_EXISTS,
  ER_PN_EXISTS,
  ER_EMAIL_NOT_REG,
  ER_PN_NOT_REG,
  ER_INVALID_PASS,
  ER_SECRET_KEY_ABSENT,
  ER_UNAUTHORIZED,
  ER_FORBIDDEN,
  ER_PRODUCT_DOES_NOT_EXIST,
  ER_PRODUCT_QUANTITY_NOT_UPDATED,
  ER_PRODUCT_NOT_DELETED,
  ER_PRODUCT_NOT_FOUND,
  ER_PRODUCT_NOT_FETCHED,
  ER_FILE_NOT_IMAGE
};

export default ErrorCodes;
